In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
le = LabelEncoder()
norm  = MinMaxScaler()

from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("C:/Users/HP/OneDrive/Desktop/DataAnalysisFiles/Datasets/brain_stroke.csv")
data.head()


gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

In [3]:
#Missing values checking
data.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [4]:
#Initailize the data
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
X

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  
0             Urban             228.69  36.6  formerly smoked  
1             Rural             105.92  32.5     never smoked  
2             Urban             171.23  34.4           smokes  
3             Rural             174.12  24.0     never smoked  
4             Urban             186.21  29.0  formerly smoked  
...             ...                ...   ...              ...  
4976          Rural              70.15  29.8  formerly smoked  
4977          Urban             191.15  31.1           smokes  
4978          Rural              95.02  31.8           smokes  
4979          Rural              83.94  30.0           smokes  
4980          Urban              83.75  29.1     never smoked  

[4981 rows x 10 columns]

In [18]:
# Label_Encoding
cat = data.select_dtypes(include='object').columns
cat

Index(['gender', 'ever_married', 'work_type', 'Residence_type',
       'smoking_status'],
      dtype='object')

In [24]:
for i in range(len(cat)):
    X[cat[i]] = le.fit_transform(X[cat[i]])

In [25]:
X

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          1   
1          1  80.0             0              1             1          1   
2          0  49.0             0              0             1          1   
3          0  79.0             1              0             1          2   
4          1  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          1   
4977       1  40.0             0              0             1          1   
4978       0  45.0             1              0             1          0   
4979       1  40.0             0              0             1          1   
4980       0  80.0             1              0             1          1   

      Residence_type  avg_glucose_level   bmi  smoking_status  
0                  1             228.69  36.6               1  
1                  0             105.92  32.5               2  
2                  1             171.23  34.4               3  
3                  0             174.12  24.0               2  
4                  1             186.21  29.0               1  
...              ...                ...   ...             ...  
4976               0              70.15  29.8               1  
4977               1             191.15  31.1               3  
4978               0              95.02  31.8               3  
4979               0              83.94  30.0               3  
4980               1              83.75  29.1               2  

[4981 rows x 10 columns]

In [26]:
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Logistic Regression

In [27]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(X_train,y_train)
y_log = log.predict(X_test)
accuracy_score(y_test,y_log)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9478260869565217

# KNN

In [35]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train,y_train)
y_knn = knn.predict(X_test)
accuracy_score(y_test,y_knn)

0.945819397993311

# Decision Tree

In [40]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
y_dtree = dtree.predict(X_test)
accuracy_score(y_test,y_dtree)

0.9036789297658863

# RandomForest Classifier


In [41]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train,y_train)
y_clf = clf.predict(X_test)
accuracy_score(y_test,y_clf)

0.9451505016722408

# SVM

In [42]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train,y_train)
y_svc = svc.predict(X_test)
accuracy_score(y_test,y_svc)

0.9478260869565217

# Threshold Values

In [43]:
def select_threshold(model,X_test,threshold):
    return np.where(np.round(model.predict_proba(X_test)[:,0],3)>=threshold,0,1)

In [47]:
#Predicting the threshold
from sklearn.metrics import confusion_matrix
for i in np.round(np.arange(0.1,1,0.1),1):
    y_pred = select_threshold(clf,X_test,i)
    print("Threshold value:",i)
    print("Confussion Matrix")
    print(confusion_matrix(y_test,y_pred))
    print("Accuracy Score = ",accuracy_score(y_test,y_pred),"\n")
    

Threshold value: 0.1
Confussion Matrix
[[1417    0]
 [  78    0]]
Accuracy Score =  0.9478260869565217 

Threshold value: 0.2
Confussion Matrix
[[1417    0]
 [  78    0]]
Accuracy Score =  0.9478260869565217 

Threshold value: 0.3
Confussion Matrix
[[1417    0]
 [  78    0]]
Accuracy Score =  0.9478260869565217 

Threshold value: 0.4
Confussion Matrix
[[1416    1]
 [  78    0]]
Accuracy Score =  0.9471571906354515 

Threshold value: 0.5
Confussion Matrix
[[1413    4]
 [  78    0]]
Accuracy Score =  0.9451505016722408 

Threshold value: 0.6
Confussion Matrix
[[1407   10]
 [  77    1]]
Accuracy Score =  0.9418060200668896 

Threshold value: 0.7
Confussion Matrix
[[1401   16]
 [  69    9]]
Accuracy Score =  0.9431438127090301 

Threshold value: 0.8
Confussion Matrix
[[1347   70]
 [  61   17]]
Accuracy Score =  0.9123745819397994 

Threshold value: 0.9
Confussion Matrix
[[1210  207]
 [  33   45]]
Accuracy Score =  0.8394648829431438 

